version: "2"
linters:
  enable:
    - bodyclose
    - cyclop
    - durationcheck
    - errorlint
    - copyloopvar
    - gocritic
    - gosec
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - unconvert
    - whitespace
    - sloglint
    - containedctx
  settings:
    cyclop:
      max-complexity: 18
