linters:
  enable:
    - bodyclose
    - cyclop
    - durationcheck
    - errorlint
    - copyloopvar
    - gocritic
    - gosec
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - unconvert
    - whitespace
    - sloglint
    - containedctx
linters-settings:
  cyclop:
    max-complexity: 18
#issues:
#  include:
#    - EXC0002 # disable excluding of issues about comments from golint
