// Code generated by make_resources.go; DO NOT EDIT.
package resources

import (
	"golang.org/x/text/feature/plural"
	"golang.org/x/text/language"

	"github.com/razor-1/cldr"
)

type pluralForms []plural.Form
type pluralFunc func(ops *cldr.PluralOperands) plural.Form

func cardinal_0() cldr.PluralData {
	// for locales: [bm bo dz hnj id ig ii in ja jbo jv jw kde kea km ko lkt lo ms my nqo osa root sah ses sg su th to tpi vi wo yo yue zh]
	forms := pluralForms{
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_1() cldr.PluralData {
	// for locales: [am as bn doi fa gu hi kn pcm zu]
	forms := pluralForms{
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// i = 0 or n = 1
		if intEqualsAny(ops.I, 0) ||
			ops.NEqualsAny(1) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_2() cldr.PluralData {
	// for locales: [ff hy kab]
	forms := pluralForms{
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// i = 0,1
		if intEqualsAny(ops.I, 0, 1) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_3() cldr.PluralData {
	// for locales: [ast de en et fi fy gl ia io ji lij nl sc sv sw ur yi]
	forms := pluralForms{
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// i = 1 and v = 0
		if intEqualsAny(ops.I, 1) && intEqualsAny(ops.V, 0) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_4() cldr.PluralData {
	// for locales: [si]
	forms := pluralForms{
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 0,1 or i = 0 and f = 1
		if ops.NEqualsAny(0, 1) ||
			intEqualsAny(ops.I, 0) && intEqualsAny(ops.F, 1) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_5() cldr.PluralData {
	// for locales: [ak bho csw guw ln mg nso pa ti wa]
	forms := pluralForms{
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 0..1
		if ops.NInRange(0, 1) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_6() cldr.PluralData {
	// for locales: [tzm]
	forms := pluralForms{
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 0..1 or n = 11..99
		if ops.NInRange(0, 1) ||
			ops.NInRange(11, 99) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_7() cldr.PluralData {
	// for locales: [af an asa az bal bem bez bg brx ce cgg chr ckb dv ee el eo eu fo fur gsw ha haw hu jgo jmc ka kaj kcg kk kkj kl ks ksb ku ky lb lg mas mgo ml mn mr nah nb nd ne nn nnh no nr ny nyn om or os pap ps rm rof rwk saq sd sdh seh sn so sq ss ssy st syr ta te teo tig tk tn tr ts ug uz ve vo vun wae xh xog]
	forms := pluralForms{
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 1
		if ops.NEqualsAny(1) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_8() cldr.PluralData {
	// for locales: [da]
	forms := pluralForms{
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 1 or t != 0 and i = 0,1
		if ops.NEqualsAny(1) ||
			!intEqualsAny(ops.T, 0) && intEqualsAny(ops.I, 0, 1) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_9() cldr.PluralData {
	// for locales: [is]
	forms := pluralForms{
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// t = 0 and i % 10 = 1 and i % 100 != 11 or t % 10 = 1 and t % 100 != 11
		if intEqualsAny(ops.T, 0) && intEqualsAny(ops.I%10, 1) && !intEqualsAny(ops.I%100, 11) ||
			intEqualsAny(ops.T%10, 1) && !intEqualsAny(ops.T%100, 11) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_10() cldr.PluralData {
	// for locales: [mk]
	forms := pluralForms{
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// v = 0 and i % 10 = 1 and i % 100 != 11 or f % 10 = 1 and f % 100 != 11
		if intEqualsAny(ops.V, 0) && intEqualsAny(ops.I%10, 1) && !intEqualsAny(ops.I%100, 11) ||
			intEqualsAny(ops.F%10, 1) && !intEqualsAny(ops.F%100, 11) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_11() cldr.PluralData {
	// for locales: [ceb fil tl]
	forms := pluralForms{
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// v = 0 and i = 1,2,3 or v = 0 and i % 10 != 4,6,9 or v != 0 and f % 10 != 4,6,9
		if intEqualsAny(ops.V, 0) && intEqualsAny(ops.I, 1, 2, 3) ||
			intEqualsAny(ops.V, 0) && !intEqualsAny(ops.I%10, 4, 6, 9) ||
			!intEqualsAny(ops.V, 0) && !intEqualsAny(ops.F%10, 4, 6, 9) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_12() cldr.PluralData {
	// for locales: [lv prg]
	forms := pluralForms{
		plural.Zero,
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n % 10 = 0 or n % 100 = 11..19 or v = 2 and f % 100 = 11..19
		if ops.NModEqualsAny(10, 0) ||
			ops.NModInRange(100, 11, 19) ||
			intEqualsAny(ops.V, 2) && intInRange(ops.F%100, 11, 19) {
			return plural.Zero
		}
		// n % 10 = 1 and n % 100 != 11 or v = 2 and f % 10 = 1 and f % 100 != 11 or v != 2 and f % 10 = 1
		if ops.NModEqualsAny(10, 1) && !ops.NModEqualsAny(100, 11) ||
			intEqualsAny(ops.V, 2) && intEqualsAny(ops.F%10, 1) && !intEqualsAny(ops.F%100, 11) ||
			!intEqualsAny(ops.V, 2) && intEqualsAny(ops.F%10, 1) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_13() cldr.PluralData {
	// for locales: [lag]
	forms := pluralForms{
		plural.Zero,
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 0
		if ops.NEqualsAny(0) {
			return plural.Zero
		}
		// i = 0,1 and n != 0
		if intEqualsAny(ops.I, 0, 1) && !ops.NEqualsAny(0) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_14() cldr.PluralData {
	// for locales: [blo]
	forms := pluralForms{
		plural.Zero,
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 0
		if ops.NEqualsAny(0) {
			return plural.Zero
		}
		// n = 1
		if ops.NEqualsAny(1) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_15() cldr.PluralData {
	// for locales: [ksh]
	forms := pluralForms{
		plural.Zero,
		plural.One,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 0
		if ops.NEqualsAny(0) {
			return plural.Zero
		}
		// n = 1
		if ops.NEqualsAny(1) {
			return plural.One
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_16() cldr.PluralData {
	// for locales: [he iw]
	forms := pluralForms{
		plural.One,
		plural.Two,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// i = 1 and v = 0 or i = 0 and v != 0
		if intEqualsAny(ops.I, 1) && intEqualsAny(ops.V, 0) ||
			intEqualsAny(ops.I, 0) && !intEqualsAny(ops.V, 0) {
			return plural.One
		}
		// i = 2 and v = 0
		if intEqualsAny(ops.I, 2) && intEqualsAny(ops.V, 0) {
			return plural.Two
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_17() cldr.PluralData {
	// for locales: [iu naq sat se sma smi smj smn sms]
	forms := pluralForms{
		plural.One,
		plural.Two,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 1
		if ops.NEqualsAny(1) {
			return plural.One
		}
		// n = 2
		if ops.NEqualsAny(2) {
			return plural.Two
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_18() cldr.PluralData {
	// for locales: [shi]
	forms := pluralForms{
		plural.One,
		plural.Few,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// i = 0 or n = 1
		if intEqualsAny(ops.I, 0) ||
			ops.NEqualsAny(1) {
			return plural.One
		}
		// n = 2..10
		if ops.NInRange(2, 10) {
			return plural.Few
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_19() cldr.PluralData {
	// for locales: [mo ro]
	forms := pluralForms{
		plural.One,
		plural.Few,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// i = 1 and v = 0
		if intEqualsAny(ops.I, 1) && intEqualsAny(ops.V, 0) {
			return plural.One
		}
		// v != 0 or n = 0 or n != 1 and n % 100 = 1..19
		if !intEqualsAny(ops.V, 0) ||
			ops.NEqualsAny(0) ||
			!ops.NEqualsAny(1) && ops.NModInRange(100, 1, 19) {
			return plural.Few
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_20() cldr.PluralData {
	// for locales: [bs hr sh sr]
	forms := pluralForms{
		plural.One,
		plural.Few,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// v = 0 and i % 10 = 1 and i % 100 != 11 or f % 10 = 1 and f % 100 != 11
		if intEqualsAny(ops.V, 0) && intEqualsAny(ops.I%10, 1) && !intEqualsAny(ops.I%100, 11) ||
			intEqualsAny(ops.F%10, 1) && !intEqualsAny(ops.F%100, 11) {
			return plural.One
		}
		// v = 0 and i % 10 = 2..4 and i % 100 != 12..14 or f % 10 = 2..4 and f % 100 != 12..14
		if intEqualsAny(ops.V, 0) && intInRange(ops.I%10, 2, 4) && !intInRange(ops.I%100, 12, 14) ||
			intInRange(ops.F%10, 2, 4) && !intInRange(ops.F%100, 12, 14) {
			return plural.Few
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_21() cldr.PluralData {
	// for locales: [fr]
	forms := pluralForms{
		plural.One,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// i = 0,1
		if intEqualsAny(ops.I, 0, 1) {
			return plural.One
		}
		// e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5
		if intEqualsAny(ops.C, 0) && !intEqualsAny(ops.I, 0) && intEqualsAny(ops.I%1000000, 0) && intEqualsAny(ops.V, 0) ||
			!intInRange(ops.C, 0, 5) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_22() cldr.PluralData {
	// for locales: [pt]
	forms := pluralForms{
		plural.One,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// i = 0..1
		if intInRange(ops.I, 0, 1) {
			return plural.One
		}
		// e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5
		if intEqualsAny(ops.C, 0) && !intEqualsAny(ops.I, 0) && intEqualsAny(ops.I%1000000, 0) && intEqualsAny(ops.V, 0) ||
			!intInRange(ops.C, 0, 5) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_23() cldr.PluralData {
	// for locales: [ca it lld pt_PT scn vec]
	forms := pluralForms{
		plural.One,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// i = 1 and v = 0
		if intEqualsAny(ops.I, 1) && intEqualsAny(ops.V, 0) {
			return plural.One
		}
		// e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5
		if intEqualsAny(ops.C, 0) && !intEqualsAny(ops.I, 0) && intEqualsAny(ops.I%1000000, 0) && intEqualsAny(ops.V, 0) ||
			!intInRange(ops.C, 0, 5) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_24() cldr.PluralData {
	// for locales: [es]
	forms := pluralForms{
		plural.One,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 1
		if ops.NEqualsAny(1) {
			return plural.One
		}
		// e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5
		if intEqualsAny(ops.C, 0) && !intEqualsAny(ops.I, 0) && intEqualsAny(ops.I%1000000, 0) && intEqualsAny(ops.V, 0) ||
			!intInRange(ops.C, 0, 5) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_25() cldr.PluralData {
	// for locales: [gd]
	forms := pluralForms{
		plural.One,
		plural.Two,
		plural.Few,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 1,11
		if ops.NEqualsAny(1, 11) {
			return plural.One
		}
		// n = 2,12
		if ops.NEqualsAny(2, 12) {
			return plural.Two
		}
		// n = 3..10,13..19
		if ops.NInRange(3, 10) || ops.NInRange(13, 19) {
			return plural.Few
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_26() cldr.PluralData {
	// for locales: [sl]
	forms := pluralForms{
		plural.One,
		plural.Two,
		plural.Few,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// v = 0 and i % 100 = 1
		if intEqualsAny(ops.V, 0) && intEqualsAny(ops.I%100, 1) {
			return plural.One
		}
		// v = 0 and i % 100 = 2
		if intEqualsAny(ops.V, 0) && intEqualsAny(ops.I%100, 2) {
			return plural.Two
		}
		// v = 0 and i % 100 = 3..4 or v != 0
		if intEqualsAny(ops.V, 0) && intInRange(ops.I%100, 3, 4) ||
			!intEqualsAny(ops.V, 0) {
			return plural.Few
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_27() cldr.PluralData {
	// for locales: [dsb hsb]
	forms := pluralForms{
		plural.One,
		plural.Two,
		plural.Few,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// v = 0 and i % 100 = 1 or f % 100 = 1
		if intEqualsAny(ops.V, 0) && intEqualsAny(ops.I%100, 1) ||
			intEqualsAny(ops.F%100, 1) {
			return plural.One
		}
		// v = 0 and i % 100 = 2 or f % 100 = 2
		if intEqualsAny(ops.V, 0) && intEqualsAny(ops.I%100, 2) ||
			intEqualsAny(ops.F%100, 2) {
			return plural.Two
		}
		// v = 0 and i % 100 = 3..4 or f % 100 = 3..4
		if intEqualsAny(ops.V, 0) && intInRange(ops.I%100, 3, 4) ||
			intInRange(ops.F%100, 3, 4) {
			return plural.Few
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_28() cldr.PluralData {
	// for locales: [cs sk]
	forms := pluralForms{
		plural.One,
		plural.Few,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// i = 1 and v = 0
		if intEqualsAny(ops.I, 1) && intEqualsAny(ops.V, 0) {
			return plural.One
		}
		// i = 2..4 and v = 0
		if intInRange(ops.I, 2, 4) && intEqualsAny(ops.V, 0) {
			return plural.Few
		}
		// v != 0
		if !intEqualsAny(ops.V, 0) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_29() cldr.PluralData {
	// for locales: [pl]
	forms := pluralForms{
		plural.One,
		plural.Few,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// i = 1 and v = 0
		if intEqualsAny(ops.I, 1) && intEqualsAny(ops.V, 0) {
			return plural.One
		}
		// v = 0 and i % 10 = 2..4 and i % 100 != 12..14
		if intEqualsAny(ops.V, 0) && intInRange(ops.I%10, 2, 4) && !intInRange(ops.I%100, 12, 14) {
			return plural.Few
		}
		// v = 0 and i != 1 and i % 10 = 0..1 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 12..14
		if intEqualsAny(ops.V, 0) && !intEqualsAny(ops.I, 1) && intInRange(ops.I%10, 0, 1) ||
			intEqualsAny(ops.V, 0) && intInRange(ops.I%10, 5, 9) ||
			intEqualsAny(ops.V, 0) && intInRange(ops.I%100, 12, 14) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_30() cldr.PluralData {
	// for locales: [be]
	forms := pluralForms{
		plural.One,
		plural.Few,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n % 10 = 1 and n % 100 != 11
		if ops.NModEqualsAny(10, 1) && !ops.NModEqualsAny(100, 11) {
			return plural.One
		}
		// n % 10 = 2..4 and n % 100 != 12..14
		if ops.NModInRange(10, 2, 4) && !ops.NModInRange(100, 12, 14) {
			return plural.Few
		}
		// n % 10 = 0 or n % 10 = 5..9 or n % 100 = 11..14
		if ops.NModEqualsAny(10, 0) ||
			ops.NModInRange(10, 5, 9) ||
			ops.NModInRange(100, 11, 14) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_31() cldr.PluralData {
	// for locales: [lt]
	forms := pluralForms{
		plural.One,
		plural.Few,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n % 10 = 1 and n % 100 != 11..19
		if ops.NModEqualsAny(10, 1) && !ops.NModInRange(100, 11, 19) {
			return plural.One
		}
		// n % 10 = 2..9 and n % 100 != 11..19
		if ops.NModInRange(10, 2, 9) && !ops.NModInRange(100, 11, 19) {
			return plural.Few
		}
		// f != 0
		if !intEqualsAny(ops.F, 0) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_32() cldr.PluralData {
	// for locales: [ru uk]
	forms := pluralForms{
		plural.One,
		plural.Few,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// v = 0 and i % 10 = 1 and i % 100 != 11
		if intEqualsAny(ops.V, 0) && intEqualsAny(ops.I%10, 1) && !intEqualsAny(ops.I%100, 11) {
			return plural.One
		}
		// v = 0 and i % 10 = 2..4 and i % 100 != 12..14
		if intEqualsAny(ops.V, 0) && intInRange(ops.I%10, 2, 4) && !intInRange(ops.I%100, 12, 14) {
			return plural.Few
		}
		// v = 0 and i % 10 = 0 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 11..14
		if intEqualsAny(ops.V, 0) && intEqualsAny(ops.I%10, 0) ||
			intEqualsAny(ops.V, 0) && intInRange(ops.I%10, 5, 9) ||
			intEqualsAny(ops.V, 0) && intInRange(ops.I%100, 11, 14) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_33() cldr.PluralData {
	// for locales: [br]
	forms := pluralForms{
		plural.One,
		plural.Two,
		plural.Few,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n % 10 = 1 and n % 100 != 11,71,91
		if ops.NModEqualsAny(10, 1) && !ops.NModEqualsAny(100, 11, 71, 91) {
			return plural.One
		}
		// n % 10 = 2 and n % 100 != 12,72,92
		if ops.NModEqualsAny(10, 2) && !ops.NModEqualsAny(100, 12, 72, 92) {
			return plural.Two
		}
		// n % 10 = 3..4,9 and n % 100 != 10..19,70..79,90..99
		if (ops.NModInRange(10, 3, 4) || ops.NModEqualsAny(10, 9)) && !(ops.NModInRange(100, 10, 19) || ops.NModInRange(100, 70, 79) || ops.NModInRange(100, 90, 99)) {
			return plural.Few
		}
		// n != 0 and n % 1000000 = 0
		if !ops.NEqualsAny(0) && ops.NModEqualsAny(1000000, 0) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_34() cldr.PluralData {
	// for locales: [mt]
	forms := pluralForms{
		plural.One,
		plural.Two,
		plural.Few,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 1
		if ops.NEqualsAny(1) {
			return plural.One
		}
		// n = 2
		if ops.NEqualsAny(2) {
			return plural.Two
		}
		// n = 0 or n % 100 = 3..10
		if ops.NEqualsAny(0) ||
			ops.NModInRange(100, 3, 10) {
			return plural.Few
		}
		// n % 100 = 11..19
		if ops.NModInRange(100, 11, 19) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_35() cldr.PluralData {
	// for locales: [ga]
	forms := pluralForms{
		plural.One,
		plural.Two,
		plural.Few,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 1
		if ops.NEqualsAny(1) {
			return plural.One
		}
		// n = 2
		if ops.NEqualsAny(2) {
			return plural.Two
		}
		// n = 3..6
		if ops.NInRange(3, 6) {
			return plural.Few
		}
		// n = 7..10
		if ops.NInRange(7, 10) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_36() cldr.PluralData {
	// for locales: [gv]
	forms := pluralForms{
		plural.One,
		plural.Two,
		plural.Few,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// v = 0 and i % 10 = 1
		if intEqualsAny(ops.V, 0) && intEqualsAny(ops.I%10, 1) {
			return plural.One
		}
		// v = 0 and i % 10 = 2
		if intEqualsAny(ops.V, 0) && intEqualsAny(ops.I%10, 2) {
			return plural.Two
		}
		// v = 0 and i % 100 = 0,20,40,60,80
		if intEqualsAny(ops.V, 0) && intEqualsAny(ops.I%100, 0, 20, 40, 60, 80) {
			return plural.Few
		}
		// v != 0
		if !intEqualsAny(ops.V, 0) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_37() cldr.PluralData {
	// for locales: [kw]
	forms := pluralForms{
		plural.Zero,
		plural.One,
		plural.Two,
		plural.Few,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 0
		if ops.NEqualsAny(0) {
			return plural.Zero
		}
		// n = 1
		if ops.NEqualsAny(1) {
			return plural.One
		}
		// n % 100 = 2,22,42,62,82 or n % 1000 = 0 and n % 100000 = 1000..20000,40000,60000,80000 or n != 0 and n % 1000000 = 100000
		if ops.NModEqualsAny(100, 2, 22, 42, 62, 82) ||
			ops.NModEqualsAny(1000, 0) && (ops.NModInRange(100000, 1000, 20000) || ops.NModEqualsAny(100000, 40000, 60000, 80000)) ||
			!ops.NEqualsAny(0) && ops.NModEqualsAny(1000000, 100000) {
			return plural.Two
		}
		// n % 100 = 3,23,43,63,83
		if ops.NModEqualsAny(100, 3, 23, 43, 63, 83) {
			return plural.Few
		}
		// n != 1 and n % 100 = 1,21,41,61,81
		if !ops.NEqualsAny(1) && ops.NModEqualsAny(100, 1, 21, 41, 61, 81) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_38() cldr.PluralData {
	// for locales: [ar ars]
	forms := pluralForms{
		plural.Zero,
		plural.One,
		plural.Two,
		plural.Few,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 0
		if ops.NEqualsAny(0) {
			return plural.Zero
		}
		// n = 1
		if ops.NEqualsAny(1) {
			return plural.One
		}
		// n = 2
		if ops.NEqualsAny(2) {
			return plural.Two
		}
		// n % 100 = 3..10
		if ops.NModInRange(100, 3, 10) {
			return plural.Few
		}
		// n % 100 = 11..99
		if ops.NModInRange(100, 11, 99) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

func cardinal_39() cldr.PluralData {
	// for locales: [cy]
	forms := pluralForms{
		plural.Zero,
		plural.One,
		plural.Two,
		plural.Few,
		plural.Many,
		plural.Other,
	}
	plFunc := func(ops *cldr.PluralOperands) plural.Form {
		// n = 0
		if ops.NEqualsAny(0) {
			return plural.Zero
		}
		// n = 1
		if ops.NEqualsAny(1) {
			return plural.One
		}
		// n = 2
		if ops.NEqualsAny(2) {
			return plural.Two
		}
		// n = 3
		if ops.NEqualsAny(3) {
			return plural.Few
		}
		// n = 6
		if ops.NEqualsAny(6) {
			return plural.Many
		}
		return plural.Other
	}

	return cldr.PluralData{Forms: forms, Func: plFunc}
}

var cardinalPlural = map[language.Tag]func() cldr.PluralData{
	tag_af:    cardinal_7,
	tag_ak:    cardinal_5,
	tag_am:    cardinal_1,
	tag_an:    cardinal_7,
	tag_ar:    cardinal_38,
	tag_ars:   cardinal_38,
	tag_as:    cardinal_1,
	tag_asa:   cardinal_7,
	tag_ast:   cardinal_3,
	tag_az:    cardinal_7,
	tag_bal:   cardinal_7,
	tag_be:    cardinal_30,
	tag_bem:   cardinal_7,
	tag_bez:   cardinal_7,
	tag_bg:    cardinal_7,
	tag_bho:   cardinal_5,
	tag_blo:   cardinal_14,
	tag_bm:    cardinal_0,
	tag_bn:    cardinal_1,
	tag_bo:    cardinal_0,
	tag_br:    cardinal_33,
	tag_brx:   cardinal_7,
	tag_bs:    cardinal_20,
	tag_ca:    cardinal_23,
	tag_ce:    cardinal_7,
	tag_ceb:   cardinal_11,
	tag_cgg:   cardinal_7,
	tag_chr:   cardinal_7,
	tag_ckb:   cardinal_7,
	tag_cs:    cardinal_28,
	tag_csw:   cardinal_5,
	tag_cy:    cardinal_39,
	tag_da:    cardinal_8,
	tag_de:    cardinal_3,
	tag_doi:   cardinal_1,
	tag_dsb:   cardinal_27,
	tag_dv:    cardinal_7,
	tag_dz:    cardinal_0,
	tag_ee:    cardinal_7,
	tag_el:    cardinal_7,
	tag_en:    cardinal_3,
	tag_eo:    cardinal_7,
	tag_es:    cardinal_24,
	tag_et:    cardinal_3,
	tag_eu:    cardinal_7,
	tag_fa:    cardinal_1,
	tag_ff:    cardinal_2,
	tag_fi:    cardinal_3,
	tag_fil:   cardinal_11,
	tag_fo:    cardinal_7,
	tag_fr:    cardinal_21,
	tag_fur:   cardinal_7,
	tag_fy:    cardinal_3,
	tag_ga:    cardinal_35,
	tag_gd:    cardinal_25,
	tag_gl:    cardinal_3,
	tag_gsw:   cardinal_7,
	tag_gu:    cardinal_1,
	tag_guw:   cardinal_5,
	tag_gv:    cardinal_36,
	tag_ha:    cardinal_7,
	tag_haw:   cardinal_7,
	tag_he:    cardinal_16,
	tag_hi:    cardinal_1,
	tag_hnj:   cardinal_0,
	tag_hr:    cardinal_20,
	tag_hsb:   cardinal_27,
	tag_hu:    cardinal_7,
	tag_hy:    cardinal_2,
	tag_ia:    cardinal_3,
	tag_id:    cardinal_0,
	tag_ig:    cardinal_0,
	tag_ii:    cardinal_0,
	tag_in:    cardinal_0,
	tag_io:    cardinal_3,
	tag_is:    cardinal_9,
	tag_it:    cardinal_23,
	tag_iu:    cardinal_17,
	tag_iw:    cardinal_16,
	tag_ja:    cardinal_0,
	tag_jbo:   cardinal_0,
	tag_jgo:   cardinal_7,
	tag_ji:    cardinal_3,
	tag_jmc:   cardinal_7,
	tag_jv:    cardinal_0,
	tag_jw:    cardinal_0,
	tag_ka:    cardinal_7,
	tag_kab:   cardinal_2,
	tag_kaj:   cardinal_7,
	tag_kcg:   cardinal_7,
	tag_kde:   cardinal_0,
	tag_kea:   cardinal_0,
	tag_kk:    cardinal_7,
	tag_kkj:   cardinal_7,
	tag_kl:    cardinal_7,
	tag_km:    cardinal_0,
	tag_kn:    cardinal_1,
	tag_ko:    cardinal_0,
	tag_ks:    cardinal_7,
	tag_ksb:   cardinal_7,
	tag_ksh:   cardinal_15,
	tag_ku:    cardinal_7,
	tag_kw:    cardinal_37,
	tag_ky:    cardinal_7,
	tag_lag:   cardinal_13,
	tag_lb:    cardinal_7,
	tag_lg:    cardinal_7,
	tag_lij:   cardinal_3,
	tag_lkt:   cardinal_0,
	tag_lld:   cardinal_23,
	tag_ln:    cardinal_5,
	tag_lo:    cardinal_0,
	tag_lt:    cardinal_31,
	tag_lv:    cardinal_12,
	tag_mas:   cardinal_7,
	tag_mg:    cardinal_5,
	tag_mgo:   cardinal_7,
	tag_mk:    cardinal_10,
	tag_ml:    cardinal_7,
	tag_mn:    cardinal_7,
	tag_mo:    cardinal_19,
	tag_mr:    cardinal_7,
	tag_ms:    cardinal_0,
	tag_mt:    cardinal_34,
	tag_my:    cardinal_0,
	tag_nah:   cardinal_7,
	tag_naq:   cardinal_17,
	tag_nb:    cardinal_7,
	tag_nd:    cardinal_7,
	tag_ne:    cardinal_7,
	tag_nl:    cardinal_3,
	tag_nn:    cardinal_7,
	tag_nnh:   cardinal_7,
	tag_no:    cardinal_7,
	tag_nqo:   cardinal_0,
	tag_nr:    cardinal_7,
	tag_nso:   cardinal_5,
	tag_ny:    cardinal_7,
	tag_nyn:   cardinal_7,
	tag_om:    cardinal_7,
	tag_or:    cardinal_7,
	tag_os:    cardinal_7,
	tag_osa:   cardinal_0,
	tag_pa:    cardinal_5,
	tag_pap:   cardinal_7,
	tag_pcm:   cardinal_1,
	tag_pl:    cardinal_29,
	tag_prg:   cardinal_12,
	tag_ps:    cardinal_7,
	tag_pt:    cardinal_22,
	tag_pt_PT: cardinal_23,
	tag_rm:    cardinal_7,
	tag_ro:    cardinal_19,
	tag_rof:   cardinal_7,
	tag_root:  cardinal_0,
	tag_ru:    cardinal_32,
	tag_rwk:   cardinal_7,
	tag_sah:   cardinal_0,
	tag_saq:   cardinal_7,
	tag_sat:   cardinal_17,
	tag_sc:    cardinal_3,
	tag_scn:   cardinal_23,
	tag_sd:    cardinal_7,
	tag_sdh:   cardinal_7,
	tag_se:    cardinal_17,
	tag_seh:   cardinal_7,
	tag_ses:   cardinal_0,
	tag_sg:    cardinal_0,
	tag_sh:    cardinal_20,
	tag_shi:   cardinal_18,
	tag_si:    cardinal_4,
	tag_sk:    cardinal_28,
	tag_sl:    cardinal_26,
	tag_sma:   cardinal_17,
	tag_smi:   cardinal_17,
	tag_smj:   cardinal_17,
	tag_smn:   cardinal_17,
	tag_sms:   cardinal_17,
	tag_sn:    cardinal_7,
	tag_so:    cardinal_7,
	tag_sq:    cardinal_7,
	tag_sr:    cardinal_20,
	tag_ss:    cardinal_7,
	tag_ssy:   cardinal_7,
	tag_st:    cardinal_7,
	tag_su:    cardinal_0,
	tag_sv:    cardinal_3,
	tag_sw:    cardinal_3,
	tag_syr:   cardinal_7,
	tag_ta:    cardinal_7,
	tag_te:    cardinal_7,
	tag_teo:   cardinal_7,
	tag_th:    cardinal_0,
	tag_ti:    cardinal_5,
	tag_tig:   cardinal_7,
	tag_tk:    cardinal_7,
	tag_tl:    cardinal_11,
	tag_tn:    cardinal_7,
	tag_to:    cardinal_0,
	tag_tpi:   cardinal_0,
	tag_tr:    cardinal_7,
	tag_ts:    cardinal_7,
	tag_tzm:   cardinal_6,
	tag_ug:    cardinal_7,
	tag_uk:    cardinal_32,
	tag_ur:    cardinal_3,
	tag_uz:    cardinal_7,
	tag_ve:    cardinal_7,
	tag_vec:   cardinal_23,
	tag_vi:    cardinal_0,
	tag_vo:    cardinal_7,
	tag_vun:   cardinal_7,
	tag_wa:    cardinal_5,
	tag_wae:   cardinal_7,
	tag_wo:    cardinal_0,
	tag_xh:    cardinal_7,
	tag_xog:   cardinal_7,
	tag_yi:    cardinal_3,
	tag_yo:    cardinal_0,
	tag_yue:   cardinal_0,
	tag_zh:    cardinal_0,
	tag_zu:    cardinal_1,
}
